apiVersion: v1
kind: Secret
metadata:
  name: doit-frontend-secret
  labels:
    app: doit-frontend
    app.kubernetes.io/part-of: doit
type: Opaque
data:
  DATABASE_URL: {{ .Values.global.databaseUrl | default "" | b64enc | quote }}
  BETTER_AUTH_SECRET: {{ .Values.global.betterAuthSecret | default "" | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.global.googleClientId | default "" | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.global.googleClientSecret | default "" | b64enc | quote }}
  GITHUB_CLIENT_ID: {{ .Values.global.githubClientId | default "" | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.global.githubClientSecret | default "" | b64enc | quote }}
